// productdata.jsx
export const mixedData = [
    {
        id: 1,
        image: './tomato.png',
        title: 'Tomato',
        description: 'Fresh and juicy tomatoes perfect for cooking.',
        price: 20,
    },
    {
        id: 2,
        image: './potato.png',
        title: 'Potato',
        description: 'High quality potatoes for any dish.',
        price: 30,
    },
    {
        id: 3,
        image: './carrot.png',
        title: 'Carrot',
        description: 'Organic carrots for healthy snacks.',
        price: 25,
    },
    {
        id: 4,
        image: './onion.png',
        title: 'Onion',
        description: 'Fresh onion for salads and more.',
        price: 35,
    },
    {
        id: 5,
        image: './noodles.png',
        title: 'Noodles',
        description: 'Tasty noodles for a satisfying meal.',
        price: 80,
    },
    {
        id: 6,
        image: './rice.png',
        title: 'Fried Rice',
        description: 'Tasty rice for a satisfying meal.',
        price: 70,
    },
    {
        id: 7,
        image: './biryani.png',
        title: 'Chicken Biryani',
        description: 'Tasty chicken biryani for a satisfying meal.',
        price: 100,
    },
    {
        id: 8,
        image: './sandwitch.png',
        title: 'sandwich',
        description: 'Tasty sandwich, for a satisfying meal.',
        price: 50,
    },
    {
        id: 9,
        image: './milk.png',
        title: 'Arokya Milk',
        description: 'Tasty milk, for a satisfying meal.',
        price: 37,
    },
    {
        id: 10,
        image: './curd.png',
        title: 'Hutsun Curd',
        description: 'Tasty curd, for a satisfying meal.',
        price: 10,
    },
    {
        id: 11,
        image: './maaza.png',
        title: 'Maaza 1Ltr',
        description: 'Tasty maaza, for a satisfying meal.',
        price: 50,
    },
    {
        id: 12,
        image: './sprite.png',
        title: 'Sprite 500ml',
        description: 'Tasty sprite, for a satisfying meal.',
        price: 25,
    },
    
]

export const medicineData = [
    {
        id: 1,
        image: './paracetamol.png',
        title: 'Paracetamol',
        description: 'Used to relieve pain and reduce fever.',
        price: 100,
    },
    {
        id: 2,
        image: './Ibuprofen.png',
        title: 'Ibuprofen',
        description: 'Commonly used to relieve pain, fever, and inflammation.',
        price: 120,
    },
    {
        id: 3,
        image: './amoxicillin.png',
        title: 'Amoxicillin',
        description: 'An antibiotic used to treat a number of bacterial infections.',
        price: 200,
    },
    {
        id: 4,
        image: './cetirizine.png',
        title: 'Cetirizine',
        description: 'Used to relieve allergy symptoms.',
        price: 90,
    },
    {
        id: 5,
        image: './omeprazole.png',
        title: 'Omeprazole',
        description: 'Reduces stomach acid to treat heartburn and GERD.',
        price: 130,
    },
    {
        id: 6,
        image: './atorvastatin.png',
        title: 'Atorvastatin',
        description: 'Used to lower cholesterol.',
        price: 210,
    },
    {
        id: 7,
        image: './metformin.png',
        title: 'Metformin',
        description: 'Used to treat type 2 diabetes.',
        price: 110,
    },
    {
        id: 8,
        image: './amlodipine.png',
        title: 'Amlodipine',
        description: 'Used to treat high blood pressure.',
        price: 140,
    },
    {
        id: 9,
        image: './lisinopril.png',
        title: 'Lisinopril',
        description: 'Used to treat high blood pressure and heart failure.',
        price: 160,
    },
    {
        id: 10,
        image: './furosemide.png',
        title: 'Furosemide',
        description: 'Used to reduce extra fluid in the body caused by conditions such as heart failure.',
        price: 150,
    },
    {
        id: 11,
        image: './losartan.png',
        title: 'Losartan',
        description: 'Used to treat high blood pressure.',
        price: 170,
    },
    {
        id: 12,
        image: './gabapentin.png',
        title: 'Gabapentin',
        description: 'Used to treat nerve pain and seizures.',
        price: 180,
    },
];


export const groceryData = [
    {
        id: 1,
        image: './tomato.png',
        title: 'Tomato',
        description: 'Fresh and juicy tomatoes perfect for cooking.',
        price: 20,
    },
    {
        id: 2,
        image: './onion.png',
        title: 'Onion',
        description: 'Fresh onion for salads and more.',
        price: 50,
    },
    {
        id: 3,
        image: './chicken.png',
        title: 'Chicken',
        description: 'Chicken for a healthy meal.',
        price: 150,
    },
    {
        id: 4,
        image: './beef.png',
        title: 'Beef',
        description: 'Beef for a hearty meal.',
        price: 200,
    },
    {
        id: 5,
        image: './salt.png',
        title: 'Tata Salt 1kg',
        description: 'Tata salt for all your cooking needs.',
        price: 100,
    },
    {
        id: 6,
        image: './chillipowder.png',
        title: 'Achi Chilli Powder 500g',
        description: 'Achi chilli powder for all your spicy needs.',
        price: 50,
    },
    {
        id: 7,
        image: './turmeric.png',
        title: 'Achi turmaric powder 100g',
        description: 'Achi turmeric powder for all your cooking needs.',
        price: 50,
    },
    {
        id: 8,
        image: './blackpepper.png',
        title: 'Black Pepper 100g',
        description: 'Black pepper for all your cooking needs.',
        price: 70,
    },
    {
        id: 9,
        image: './kotmir.png',
        title: 'Kotmir',
        description: 'Kotmir for all your cooking needs.',
        price: 10,
    },
    {
        id: 10,
        image: './pudina.png',
        title: 'Pudhina',
        description: 'Pudhina for all your cooking needs.',
        price: 10,
    },
    {
        id: 11,
        image: './aata.png',
        title: 'Aata',
        description: 'Aata for all your cooking needs.',
        price: 50,
    },
    {
        id: 12,
        image: './sugar.png',
        title: 'Sugar',
        description: 'Sugar for all your cooking needs.',
        price: 45,
    },

    // Add more products as needed
];
export const foodData = [
    {
        id: 1,
        image: './biryani.png',
        title: 'Chicken Biryani',
        description: 'Aromatic and flavorful rice dish with tender chicken.',
        price: 150,
    },
    {
        id: 2,
        image: './paneer.png',
        title: 'Paneer Butter Masala',
        description: 'Creamy and rich curry with soft paneer cubes.',
        price: 120,
    },
    {
        id: 3,
        image: './dosa.png',
        title: 'Masala Dosa',
        description: 'Crispy crepe filled with spiced potato mixture.',
        price: 50,
    },
    {
        id: 4,
        image: './samosa.png',
        title: 'Samosa',
        description: 'Deep-fried pastry with spicy potato filling.',
        price: 20,
    },
    {
        id: 5,
        image: './idli.png',
        title: 'Idli',
        description: 'Steamed rice cakes served with chutney and sambar.',
        price: 30,
    },
    {
        id: 6,
        image: './chole.png',
        title: 'Chole Bhature',
        description: 'Spicy chickpea curry served with fluffy fried bread.',
        price: 100,
    },
    {
        id: 7,
        image: './rajma.png',
        title: 'Rajma Chawal',
        description: 'Kidney beans curry served with rice.',
        price: 80,
    },
    {
        id: 8,
        image: './pavbhaji.png',
        title: 'Pav Bhaji',
        description: 'Spicy mashed vegetables served with buttered bread.',
        price: 60,
    },
    {
        id: 9,
        image: './tandoori.png',
        title: 'Tandoori Chicken',
        description: 'Grilled chicken marinated with spices and yogurt.',
        price: 180,
    },
    {
        id: 10,
        image: './dal.png',
        title: 'Dal Tadka',
        description: 'Lentil curry tempered with spices.',
        price: 70,
    },
    {
        id: 11,
        image: './kebab.png',
        title: 'Seekh Kebab',
        description: 'Minced meat skewers cooked with spices.',
        price: 90,
    },
    {
        id: 12,
        image: './poha.png',
        title: 'Poha',
        description: 'Flattened rice cooked with onions and spices.',
        price: 40,
    },
];

export const electronicsData = [
    {
        id: 1,
        image: './drill.png',
        title: 'Drill',
        description: 'Power tool for making holes in various materials.',
        price: 100,
    },
    {
        id: 2,
        image: './saw.png',
        title: 'Saw',
        description: 'Handheld power tool for cutting through wood and metal.',
        price: 80,
    },
    {
        id: 3,
        image: './multimeter.png',
        title: 'Multimeter',
        description: 'Device for measuring electrical voltage, current, and resistance.',
        price: 40,
    },
    {
        id: 4,
        image: './welder.png',
        title: 'Welder',
        description: 'Device for joining two metal pieces by applying heat.',
        price: 150,
    },
    {
        id: 5,
        image: './grinder.png',
        title: 'Grinder',
        description: 'Power tool for grinding and cutting through metal and concrete.',
        price: 120,
    },
    {
        id: 6,
        image: './solderingiron.png',
        title: 'Soldering Iron',
        description: 'Device for melting solder to join electronic components.',
        price: 50,
    },
    {
        id: 7,
        image: './wirestripper.png',
        title: 'Wire Stripper',
        description: 'Tool for removing insulation from electrical wires.',
        price: 30,
    },
    {
        id: 8,
        image: './pliers.png',
        title: 'Pliers',
        description: 'Hand tool for gripping and bending objects.',
        price: 25,
    },
    {
        id: 9,
        image: './hammer.png',
        title: 'Hammer',
        description: 'Tool for driving nails and fitting parts together.',
        price: 20,
    },
    {
        id: 10,
        image: './tape.png',
        title: 'Electrical Tape',
        description: 'Adhesive tape for insulating electrical wires.',
        price: 15,
    },
    {
        id: 11,
        image: './cableties.png',
        title: 'Cable Ties',
        description: 'Plastic strips for bundling electrical cables.',
        price: 10,
    },
    {
        id: 12,
        image: './fuse.png',
        title: 'Fuse',
        description: 'Device for protecting electrical circuits from overcurrent.',
        price: 5,
    },
];

